{
 "title": "Anbox Cloud",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (cluster_id) (ams_cluster_nodes_total))",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (cluster_id) (ams_cluster_applications_total))",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (cluster_id) (ams_cluster_containers_total))",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Available vCPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (node, cluster_id) (ams_cluster_available_cpu_total))",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Used vCPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (node, cluster_id) (ams_cluster_used_cpu_total))",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "vCPUs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor((sum(max by (node, cluster_id) (ams_cluster_used_cpu_total))/sum(max by (node, cluster_id) (ams_cluster_available_cpu_total)))*100)"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (node, cluster_id) (ams_cluster_available_memory_total))/(1024*1024)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (node, cluster_id) (ams_cluster_used_memory_total))/(1024*1024)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor((sum(max by (node, cluster_id) (ams_cluster_used_memory_total))/sum(max by (node, cluster_id) (ams_cluster_available_memory_total)))*100)"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "# Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max by (cluster_id) (ams_cluster_containers_total))",
     "legendFormat": "All containers"
    },
    {
     "expr": "sum(max by (cluster_id) (ams_cluster_containers_per_status_total{status=\"error\"}))",
     "legendFormat": "Failed containers"
    }
   ]
  },
  {
   "title": "Container boot time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "boot time" }
   ],
   "targets": [
    {
     "expr": "sum(max by (cluster_id) (rate(ams_cluster_container_boot_time_seconds_sum[5m]))) / sum(max by (cluster_id) (rate(ams_cluster_container_boot_time_seconds_count[5m])))",
     "legendFormat": "avg boot time (5m)"
    }
   ]
  },
  { "title": "Cluster System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_load1{juju_application=\"lxd\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "avg(system_load5{juju_application=\"lxd\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "avg(system_load15{juju_application=\"lxd\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(cpu_usage_user)", "legendFormat": "user" },
    { "expr": "avg(cpu_usage_system)", "legendFormat": "system" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(mem_used{juju_application=\"lxd\"})",
     "legendFormat": "used"
    },
    {
     "expr": "avg(mem_available{juju_application=\"lxd\"})",
     "legendFormat": "available"
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Average FPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(fps)", "legendFormat": "FPS" }
   ]
  },
  {
   "title": "FPS stddev",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stddev(fps)", "legendFormat": "FPS (stddev)" }
   ]
  }
 ]
}