name: Build/Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux, X64, jammy, large]
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: [self-hosted, linux, X64, jammy, large]
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v13.0.0
    with:
      cache: true

  collect-tests:
    name: Collect tests for charms
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Assign charm artifacts to runners
      id: charm-to-runner
      run: |
        # Reverse lookup for artifact base index to its architecture
        ./scripts/ci/get-runners.py
        cat $GITHUB_OUTPUT
    outputs:
      bases: ${{ steps.charm-to-runner.outputs.bases }}

  integration-test:
    name: Integration tests
    needs:
      - lint
      - unit-test
      - collect-tests
      - build
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        agent-versions:
          - "3.2.2"  # renovate: latest juju 3
          - "2.9.44"  # renovate: latest juju 2
        base: ${{ fromJSON(needs.collect-tests.outputs.bases) }}
    runs-on: "${{matrix.base.runner_labels}}"
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Download packed charm(s)
        uses: actions/download-artifact@v4
        id: downloaded-charm
        with:
          name: ${{ needs.build.outputs.artifact-prefix }}-base-${{ matrix.base.base_index }}
      - name: Set channel
        run: |
          juju_channel=$(echo "${{ matrix.agent-versions }}" | cut -c 1-3)
          echo "channel=${juju_channel}/stable" >> "$GITHUB_ENV"
          juju_major=$(echo "${{ matrix.agent-versions }}" | cut -c 1)
          echo "libjuju=juju${juju_major}" >> "$GITHUB_ENV"
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: "${{ env.channel }}"
          bootstrap-options: "--agent-version ${{ matrix.agent-versions }}"
      - name: Run integration tests
        env:
            snap_channel: 1.21/stable
        run: |
          mv ${{ steps.downloaded-charm.outputs.download-path }}/*.charm ams.charm
          args="--charm=./ams.charm"
          if [ "${{ matrix.base.arch }}" == "arm64" ]; then
            args="${args} --constraints arch=arm64"
          fi
          tox -e integration-${{ env.libjuju }} -- ${args}
