name: Get current charm version

on:
  workflow_call:
    outputs:
      charm_version:
        description: "Get the current version of the charm"
        value: ${{ jobs.get-charm-version.outputs.version }}

jobs:
  get-charm-version:
    runs-on: [self-hosted, linux, X64, jammy, large]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Get charm version
        id: charm_version
        run: |
          echo "version=$(cat version)" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.charm_version.outputs.version }}

