on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'
      - 'docs/**'
      - .github/renovate.json5
      - pyproject.toml

jobs:
  ci:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yaml
    secrets: inherit

  release:
    name: Release charm
    needs:
      - ci
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@v13.0.0
    with:
      # TODO: change this when we actually want to cutover the charm to main
      # channels
      channel: 1.21-ops/edge
      artifact-prefix: ${{ needs.ci.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
