name: Release To Edge

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'
      - 'docs/**'
      - .github/renovate.json5
      - pyproject.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-version:
    name: Get Charm Version
    uses: ./.github/workflows/get-version.yaml

  ci:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yaml
    secrets: inherit
    with:
      snap_risk_level: edge

  release:
    name: Release to edge
    needs:
      - ci
      - get-version
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@58f047f7eebbde23770e7058d3f62f88ce7fe0dd # v16.3.0
    with:
      # TODO: change this when we actually want to cutover the charm to main
      # channels
      channel: "${{ needs.get-version.outputs.charm_version }}-ops/edge"
      artifact-prefix: ${{ needs.ci.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
